### ISSUE TITLE
for large graphs, can you add the overlap=scale option to Graphviz?

### ISSUE THREAD

**Issue by kenyee** [jraska/modules-graph-assert#148]
See: https://stackoverflow.com/questions/13417411/laying-out-a-large-graph-with-graphviz

We have a 650 module android project and Graphviz's dot->png generation takes over an hour...

Or output a file for Gephi to look through?

It could also use some sort of status printout/update of "e.g. processed X modules" while it's working....2 hours+.
Similar issue w/ the module generateModulesGraphStatistics command.

**Comment by jraska** [comment]
Hi Ken,

Thanks for reaching out and raising this. How many edges and height the graph has? It would help with reproducing the issue.

If I understand it correctly it is the Graphviz png generation, which takes over an hour in case of the graph and in case of `generateModulesGraphStatistics` is it the plugin itself? Or it is the `generateModulesGraphvizText ` task run which takes 1 hour+?

> Graphviz's dot->png generation takes over an hour

The Graphviz export is a helper function of the plugin and I think I will not go through path to support individual [attributes](https://graphviz.org/doc/info/attrs.html) as I would like to avoid focusing on the Graphviz complexity too much. 
The text within `dot` file generated by module-graph-assert plugin could be edited anyhow so wouldn't just editing it from your side before be a feasible solution? 

>  some sort of status printout/update of "e.g. processed X modules"

For the statistics it is the `generateModulesGraphStatistics` task itself which takes 2 hours+ I would assume it is searching for the longest path. I would prefer tackling the problem rather by speeding up the plugin as only naive implementation of finding the [longest path](https://github.com/jraska/modules-graph-assert/blob/master/plugin/src/main/kotlin/com/jraska/module/graph/DependencyGraph.kt#L30) and [root](https://github.com/jraska/modules-graph-assert/blob/master/plugin/src/main/kotlin/com/jraska/module/graph/DependencyGraph.kt#L8) is being used.

So if I get more understanding and ideally if you could somehow send me a the dot file it would massively speed up improving the performance - potentially with renamed modules to keep your proprietary info :) 

Thanks

**Comment by jraska** [comment]
So the graph heigh calculation is currently with exponential complexity - unnecessarily. One quick thing we can try is if you please could checkout this repo and include it [to your project as explained here](https://github.com/jraska/modules-graph-assert#debugging) with [this modification](https://drive.google.com/file/d/1r6IFXNTeZDNt3J_ym6Nm4SaZNawRqP0X/view?usp=sharing).

This could dramatically cut down the execution times. If it works I will need to do a bit more modifications, but it wouldn't be much work to move this to next release once we verify it is the solution to your problem.

**Comment by kenyee** [comment]
hmm..I thought it generated a PNG (first time trying to run it and it still hasn't finished...up to 4hrs so far).  I'm running both commands in different windows since they appear to be single threaded.
I'll try that...thanks.

**Comment by kenyee** [comment]
Thanks....that let stats run in 56sec :-)
GraphStatistics(modulesCount=672, edgesCount=5789, height=64, ...

**Comment by jraska** [comment]
Nice, thanks! 

I will move the changes to master once I have time for it and release version `2.0.1`, though it requires a bit more changes so might take some time. :)

I will update this issue once it happens.

**Comment by jraska** [comment]
The improvement is merged into master and I will release it soon.

One interesting thing is that I tried even with graph:
`modulesCount=20_001, edgesCount=2_000_198, height=447` and the calculations took 2 seconds on old MacBook Pro 2013 machine.

@kenyee I'm still trying to think where these `56sec` are coming from? Was it a full Gradle execution or only the task duration time? The statistics task should be now pretty fast. :)

**Comment by jraska** [comment]
Released with [version 2.1.0](https://github.com/jraska/modules-graph-assert/releases/tag/2.1.0)

I'm closing the issue, but I still would be curious about the total timing of 56sec to know if there is more to optimize.

Thanks!

**Comment by kenyee** [comment]
> @kenyee I'm still trying to think where these `56sec` are coming from? Was it a full Gradle execution or only the task duration time? The statistics task should be now pretty fast. :)

Your plugin requires the gradle run to be done w/ the configuration cache disabled.
We have 650 modules, so that takes a while for Gradle to parse..

**Comment by jraska** [comment]
> the configuration cache disabled

This is no longer required :) see [#120](https://github.com/jraska/modules-graph-assert/issues/120#issuecomment-977158287)

There still might be a need for `--no-configure-on-demand` in case the plugin is applied to some module which would allow Gradle not to configure some modules - making them invisible for the plugin.

> takes a while for Gradle to parse

Cool, so it is not the task speed anymore. Thanks

**Comment by kenyee** [comment]
yep, --no-configure-on-demand is what I mean...
