### ISSUE TITLE
feature request: add a way to add GraphViz node attributes

### ISSUE THREAD

**Issue by kenyee** [jraska/modules-graph-assert#149]
Would be nice to be able to color code them like this:
https://reposhub.com/android/gradle/vanniktech-gradle-dependency-graph-generator-plugin.html
or change shapes of the nodes...

If we had some sort of DSL where we could supply a callback that can add attributes depending on the module name/path, that would make this possible.

**Comment by jraska** [comment]
Hi Ken,

Thanks for the idea.

The Graphviz export is only a helper function of the plugin and I think I will not go through path to support more functionality as I would like to avoid focusing on the Graphviz complexity too much.

I can imagine that this might mean some hookable abstraction, but for now I don't want to increase the scope of the plugin as the Graphviz export should serve only to navigate into proper assertions, which is the main purpose of this plugin.

If you want to implement some customizations you could always do it by the approach explained [here](https://github.com/jraska/modules-graph-assert/issues/148#issuecomment-985125125) with local changes to [`GraphvizWriter`](https://github.com/jraska/modules-graph-assert/blob/master/plugin/src/main/kotlin/com/jraska/module/graph/GraphvizWriter.kt). It is not ideal, but might enable you to do it quickly :) + it can give idea how the possible `Generator` alternative could look like. I could be convinced to include such functionality by a PR if the changes required are simple. :)

**Comment by jraska** [comment]
Closing this issue for now as "won't do". Please if you still feel that the implementation would be simple I'm happy to discuss PR anytime.

Thanks for starting the issue!
