### ISSUE TITLE
Feature idea: ModuleNameAlias overview

### ISSUE THREAD

**Issue by ILikeYourHat** [jraska/modules-graph-assert#156]
The new approach to module assertions, using "moduleNameAssertAlias", is a great idea. However, it would be nice to have a task that provides the list of all modules in project, with their corresponding alias. It comes very handy when migrating modules, to check which still need migration.

Example output might look like this:
```
ModuleAliases:
:app = App
:module1 = Implementation
:module2 = NeedsMigration
:module3 = (none)
```

**Comment by jraska** [comment]
Hi, thanks for rising the idea.

I think this can be done by this piece of Gradle script:
```
task printModuleWithAliases {
  doLast {
    subprojects.forEach { project ->
      print(project.name)
      if (project.hasProperty("moduleNameAssertAlias")) {
        print(" = ")
        print(project.property("moduleNameAssertAlias"))
      }
      println()
    }
  }
}
```

For now I think this doesn't need to be shipped with the plugin as it would be a new task and I would like to void making API bigger.

Though I will think about including the alias into the module graph printing as over there it could make sense adding the alias there. https://github.com/jraska/modules-graph-assert/issues/158

Thanks
