### ISSUE TITLE
Feature idea: ignore list

### ISSUE THREAD

**Issue by ILikeYourHat** [jraska/modules-graph-assert#157]
It would be nice to have an ignore list, that contains module connections violating the module assertions. Those connections do not fail the `check` task, they are simply ignored. The whole idea is similar to "baseline" file in Lint: we have some tech debt we don't want to deal now, but we also want to stop making more debt.

Example configuration:
```
moduleGraphAssert {
  allowed = [
    'Implementation -> Api', 
    'App -> Implementation', 
    'App -> Api'
  ]
  ignored = [
    ':module1 -> :module2'
  ]
}
```

**Comment by jraska** [comment]
Hey, thanks for reaching out.

I think for this purpose you can just mark such connection as allowed and no special ignored list is needed. Like `allowed = [ ':module1 -> :module2', ...]`
In case you want to explicitly mark some modules as tech debt, you can mark them by a special name as [in the readme](https://github.com/jraska/modules-graph-assert#module-name-alias) - `"NeedsMigration"`

Even if it is not exactly the same I think it is similar enough and having explicit ignore list is not worth added complexity to the plugin :)

**Comment by jraska** [comment]
Closing this for now as won't do. 

If you still think it cannot be achieved by current functionality I'm happy to discuss over PR.

Thanks for the started issue.
