### ISSUE TITLE
Generate image of graph with a task

### ISSUE THREAD

**Issue by yoobi** [jraska/modules-graph-assert#218]
Hello !

First of all thank you for this neat plugin, I'm still in the middle of discovering it and I'd like to generate the image of my graph directly from a task, is it possible ?

I've seen that there is `./gradlew generateModulesGraphvizText -Pmodules.graph.output.gv=fileName` which generate a description of the dependencies but couldn't find how to generate the image directly.

Thanks

**Comment by jraska** [comment]
Hey, thanks for reaching out and using the plugin.

It is not possible to generate the image directly, but you can do that by a `dot` command on the file if you install Graphviz to your machine. :)

The reason for not having task for that was simplicity.

**Comment by yoobi** [comment]
I understand, as an additional request I'm trying to automate the process of generating the image once the android project has finished building with the command: `gradle generateModulesGraphvizText -Pmodules.graph.output.gv=project.dot` but  it's not printing anything
In my `:app` module build.gradle file I've added:

```
tasks.named("afterBuild") {
    configure {
        dependsOn("generateModulesGraphvizText")
    }
}
assemble.finalizedBy("afterBuild")
```
