### ISSUE TITLE
generateModulesGraphStatistics module parameter not working correctly

### ISSUE THREAD

**Issue by JohnLeeroy** [jraska/modules-graph-assert#226]
The `generateModulesGraphStatistics` command with the `-Pmodules.graph.of.module` is only printing the root module statistics.  The task does not seem to take into account the parameter for a specified module. 

I didn't find any tests that covered the generated task with a specific parameter either so that may be a good addition to the test collection.

**Comment by jraska** [comment]
Resolved by [version 2.4.1](https://github.com/jraska/modules-graph-assert/releases/tag/2.4.1)

```
plugins {
  id "com.jraska.module.graph.assertion" version "2.4.1"
}
```
