### ISSUE TITLE
The library does not detect `rootProject` as dependency in a graph

### ISSUE THREAD

**Issue by burnoo** [jraska/modules-graph-assert#232]
In Gradle `rootProject` is a also a module and can have dependencies to other modules. In the project I'm working on, the `rootProject` wasn't extracted to the `:app` module, so it's currently "main" app module. The library does not detect it, thus it is building only a part of dependency graph.

This behavior can be easily fixed by using `Project.allprojects` instead of `Project.rootProject.subprojects` (in `GradleDependencyGraphFactory`, and maybe `GradleModuleAliasExtractor`). I've tested it locally and got a valid graph.

I could open a PR with those changes. @jraska do you think it should be a default behavior or there should be a flag to turn it on? (do you have a proposition for the flag naming then?)

EDIT: Opened https://github.com/jraska/modules-graph-assert/pull/233 with `allprojects` as a default behavior. I'm open to move this change behind a flag.

**Comment by jraska** [comment]
Hey Bruno, 
Thanks a lot for reporting this and for the PR! I wish all reported bugs would look like this 👏 🚀 

Indeed this case was never considered and assumption that root project won't have code and dependencies was made.

I will follow up on the PR - basically now the only question is if this can cause a breaking change in behaviour of some existing client so I need to think about some edge cases 🤔 

_I might be also slow to respond as I'm on holidays._

**Comment by jraska** [comment]
Fix released [in version 2.5.0](https://github.com/jraska/modules-graph-assert/releases/tag/2.5.0)

Thank you!
