### ISSUE TITLE
Allow different rules for different configurations

### ISSUE THREAD

**Issue by yogurtearl** [jraska/modules-graph-assert#244]
I would like to be able to specify that `projectA` can have an `implementation` dep on `projectB` but not an `api` dependency on `projectB`.

**Comment by jraska** [comment]
Hey, this is currently not possible directly and there are no plans to support such use case as it would likely require rethinking the asserting model.

### 1st workaround I can think of:
1. Applying the plugin on the root `build.gradle` [and configure](https://docs.gradle.org/current/samples/sample_convention_plugins.html) only for `configurations = ['implementation']` where you allow `projectA` -> `projectB`.
2. Applyng the plugin on the `projectA` and using `configurations = ['api']` restricting `projectA` -> `projectB`
3. In case you want to share configuration of `projectA` you could use [convention plugin](https://docs.gradle.org/current/samples/sample_convention_plugins.html).

### 2nd workaround
- Modifying the code([Extracting graph from Gradle](https://github.com/jraska/modules-graph-assert/blob/master/plugin/src/main/kotlin/com/jraska/module/graph/assertion/GradleDependencyGraphFactory.kt#L9), [Representation of the graph](https://github.com/jraska/modules-graph-assert/blob/master/plugin/src/main/kotlin/com/jraska/module/graph/DependencyGraph.kt)) and forking the repo + [use composite build](https://github.com/jraska/modules-graph-assert#debugging).

Please let me know if particularly option 1 works for your use case :) thanks
