### ISSUE TITLE
Longest path vs longest graph

### ISSUE THREAD

**Issue by SimonMarquis** [jraska/modules-graph-assert#246]
The plugin currently shows the longest path in red, but there are almost always multiple "longest paths" with the same size.
Unfortunately, since we only show the first match, we might not get the whole picture of the "critical graph".

https://github.com/jraska/modules-graph-assert/blob/878534738d5bb27ba04a67d0fcaec9742a1259cf/plugin/src/main/kotlin/com/jraska/module/graph/DependencyGraph.kt#L120

https://github.com/jraska/modules-graph-assert/blob/878534738d5bb27ba04a67d0fcaec9742a1259cf/plugin/src/main/kotlin/com/jraska/module/graph/DependencyGraph.kt#L98

| Longest path | Critical graph |
|---|---|
| ![graph (2)](https://github.com/jraska/modules-graph-assert/assets/1921278/a85dc911-657e-4377-be3c-c0f417cfe32a) | ![graph (3)](https://github.com/jraska/modules-graph-assert/assets/1921278/49ed57b4-a94e-4164-b999-b70ff1967303) |

Is this something that you would be interested in adding to this project?

**Comment by jraska** [comment]
Hey, thanks for the issue.

The major purpose of this plugin is the graph assertion and the graphs themselves are wide topic which is only scratched by this plugin.
Therefore no, I will not add this feature to the plugin as the graph theory opens too many possibilities :)

Two alternatives how you can proceed:

1. See the https://github.com/siggijons/graph-untangler-plugin. It will show way more data and likely give you the visibility you are after.
2. In case you want to explore how the graph will evolve after some longest path is decoupled, simply remove/comment the modules dependency - the plugin will still work. We several times used this technique to build a roadmap of decoupling modules.

**Comment by SimonMarquis** [comment]
Thanks for the heads up. Indeed, this is very similar to the "height" graph generated by graph-untangler-plugin.
