### ISSUE TITLE
Graphviz: assign all leaf modules max rank

### ISSUE THREAD

**Issue by matejdro** [jraska/modules-graph-assert#256]
For example, for the following module graph:

```
digraph G {
":A" -> ":B"
":B" -> ":C"
":C" -> ":D"
":C" -> ":E"
":B" -> ":E"
":A" -> ":F"
":B" -> ":G"
}
```

![image](https://github.com/jraska/modules-graph-assert/assets/507922/7e0830b1-2230-46f5-ae70-22d20b699ec1)

It is not very easy to see which modules can be compiled concurrently, since leaves are scattered around the entire graph.

However, adding `{ rank=max; ":D";  ":E", ":G", ":F" }` line to the generated graphviz makes this much better:

![image](https://github.com/jraska/modules-graph-assert/assets/507922/905a49b8-5cf2-4f23-a88e-a590f29221c5)

Now, we can clearly see that D, E, G and F will be compiled first, at the same time.

If accepted, I can add a PR for this.

**Comment by jraska** [comment]
Hey, thanks for raising the issue. 

I prefer not to add this functionality from 2 reasons.

1. Changing this is a change of behaviour so technically it should be a major version update.
2. The graphing functionality is a secondary feature of the plugin. I know many people use it for this, but the main purpose is graph assertion and as such I don't want to invest more in the graphing features as there is so many improvements which could go there. Better plugin for graph features is: https://github.com/siggijons/graph-untangler-plugin
