### ISSUE TITLE
Validation fails when running module specific gradle commands

### ISSUE THREAD

**Issue by max1lyu** [jraska/modules-graph-assert#260]
hey @jraska, I think this might relate to #230 issue.

The issue that I'm struggling with is running commands per individual module, the execution fails with graph validation. And it looks like graph assert plugin doesn't get the aliases about all modules. 

I was able to reproduce it on the github-client repo. Here is the [patch](https://github.com/jraska/modules-graph-assert/files/15504354/github-client-06-19-43.patch) to the current master, or [fork](https://github.com/max1lyu/github-client/tree/issue-230/graph-assert-error).

Example of such command:
```
./gradlew :feature:about:dependencies --configuration debugCompileClasspath
```

Adding `--no-configure-on-demand` helps execute the command above, but I wonder if there’s a way to fix this on the plugin side so I don’t have to explicitly tell gradle that.

**Comment by jraska** [comment]
Hey, thanks for reporting it with an example! I will have a look once I have a chance.

At the same time I think the `--no-configure-on-demand` flag will be needed as it exists precisely for the reason that Gralde avoids configuring several modules when it can.

I see now this is not documented so I will probaboy update the README with this info. :)

**Comment by jraska** [comment]
Documentation added by #263
