### ISSUE TITLE
Feature request: Add API to specify configurations from the command line

### ISSUE THREAD

**Issue by dturner** [jraska/modules-graph-assert#261]
We are using this plugin on the [Now in Android app](https://github.com/android/nowinandroid) project to visualize module dependencies ([example](https://github.com/android/nowinandroid/tree/main/app)). We generate graphs for each module using [a script](https://github.com/android/nowinandroid/blob/main/generateModuleGraphs.sh#L120) which calls `generateModulesGraphvizText`. This works great, thanks.

The module dependencies are obtained for the default configurations of `api` and `implementation`, however, we would like to also generate dependency graphs for the `test` and `androidTest` configurations as well. Would it be possible to add an [API parameter](https://github.com/jraska/modules-graph-assert/blob/4616fb5aae260302e94a1e9f177f9eeaad1c0549/plugin/src/main/kotlin/com/jraska/module/graph/assertion/Api.kt#L14) to specify configurations from the command line?

**Comment by jraska** [comment]
Hey Don,

Thanks for reaching out.

Adding the command line parameters is an option. Wouldn't though a current possible alternative be to use [configuration](module-graph) 
```
moduleGraphAssert {
  configurations = ['api', 'implementation', 'test', 'androidTest']
}
```

In the file [where you apply the plugin](https://github.com/android/nowinandroid/blob/420076f01aadd61f650b6848cd23643ca59226b8/build.gradle.kts#L51)?

I think this could be applied right now to the app to achieve what you need. :)

**Comment by dturner** [comment]
Thanks, that works great. I was able to generate graphs for just `androidTestImplementation` [here](https://github.com/android/nowinandroid/blob/dt/add-module-graphs/docs/images/graphs/dep_graph_app.svg). It's not quite as usable as being able to specify the configuration on the command line but is fine for what we need.

**Comment by jraska** [comment]
@dturner This issue actually made me think about the distinction on what should be a Gradle configuration and what a command line parameter 🤔 

When we start talking about API as a command line parameter, actually also the other [configuration](https://github.com/jraska/modules-graph-assert?tab=readme-ov-file#configuration) could have a same logic 🤔 

So if I consider adding API as command line parameters, one of the question arising is if then al l the other configurations should have command line options as well.

Any thoughs from you? :)
