### ISSUE TITLE
Unable to generate a module graph

### ISSUE THREAD

**Issue by jokoolle-183** [jraska/modules-graph-assert#271]
After adding the dependency to the plugin and attempting to generate a dependency graph for the app module, I was confronted with generation errors. 

Then I tried running a simple ./gradlew generateModulesGraphStatistics for the whole project and got this output: 

![Screenshot 2024-08-20 at 3 06 23 PM](https://github.com/user-attachments/assets/3b6f320a-1d52-49b6-b25f-dae24310a2ff)

Thinking I might have misconfigured something, I made sure I followed the implementation as in Google's Now in Android project (added plugin dependency in root level gradle file and set apply to 'true'). I tried generating the module graph in the NIA project, as well as running the statistics task and this is the result: 

![Screenshot 2024-08-20 at 3 08 18 PM](https://github.com/user-attachments/assets/a7b5b1da-83a6-4da3-b18f-62546762cdc0)

In order to debug the plugin I included it as a composite build and started digging. 
It was obvious that all the subprojects weren't getting loaded or recognized. So I played around and changed plugin initialization a bit. 

![Screenshot 2024-08-20 at 3 17 46 PM](https://github.com/user-attachments/assets/871ac2f5-70d6-40cd-82db-3d1822c5a7d4)

After applying this change, the project and all of its subprojects got loaded. 

![Screenshot 2024-08-20 at 2 59 50 PM](https://github.com/user-attachments/assets/6cbc294f-c959-40af-a3e2-54ccc32b8b3a)

In order to test this on other projects such as NIA, I forked the repo and published some versions with the above-mentioned changes to Jitpack.
This change seems to not affect the NIA project, although I only tested out generating module graphs via their script and running the statistics task. 

@jraska 
What do you think about these changes? 
Is there anything specific I'd need to take into consideration and verify? 

I know this might seem like overkill for needs of a single project, so any feedback on how we might fix this locally in order to avoid applying changes to the plugin library would be appreciated! 

P.S. Currently the project I'm working on is using the forked version of your plugin, since it's crucial to our restructuring and remodularization initiative, since we're having long build times. 
Thank you for your motivating presentation on the Droidcon and Medium articles on this topic, it's been really inspiring and one of the driving forces to resolve technical debt in our project 💪 

## UPDATE 22.8.2024

Fixed in this PR --> https://github.com/jraska/modules-graph-assert/pull/272

**Comment by jraska** [comment]
Hey, thanks for describing the issue into such detail and testing it on the way 👏 

I actually think you found a way how it should be done correctly 🤔 and I also suspect this issue was related: #230 

The bug you are experiencing is happening because the dependencies are not loaded at the moment the plugin is trying to read them.
My thinking is that `gradle.projectsEvaluated` is called after all projects are evaluated as it's name says, which is actually what the plugin assumed and it works with `project.afterEvaluate` in majority of cases, but clearly not in all of those.

Thank you very much for discovering this! Let's get that PR merged :)

**Comment by jraska** [comment]
I will keep the issue open before the release goes out. :) not fixed until released.

**Comment by jokoolle-183** [comment]
Hello @jraska, 
When can we expect the release, a rough estimation? 😄 
Just asking for the sake of general information.

**Comment by jraska** [comment]
Hey, sorry for the delay. I'm aware it's expected.

I hope max 2 weeks I need to figure out something in the background.

**Comment by jokoolle-183** [comment]
> Hey, sorry for the delay. I'm aware it's expected.
> 
> I hope max 2 weeks I need to figure out something in the background.

Okay, thanks!

**Comment by jraska** [comment]
Solved. Thanks for the patience and the contribution :)

[2.7.0](https://github.com/jraska/modules-graph-assert/releases/tag/2.7.0)

**Comment by jokoolle-183** [comment]
> Solved. Thanks for the patience and the contribution :)
> 
> [2.7.0](https://github.com/jraska/modules-graph-assert/releases/tag/2.7.0)

Awesome! 
Thank you so much 🫶

**Comment by jraska** [comment]
Hey, I will be reverting this change temporarily as it causes the tasks not to be found in many scenario without the flag `--no-configure`

### Current plan
- Revert the change and release. Version `2.7.1` to come back to stable behaviour and not lose trust of the plugin users.
- Keep the `2.7.0` out for experimenting - you can keep using it if it works for you
- Get the full understanding without time pressure
- Come up with final proposal - `--no-configure-on-demand` being mandatory is a likely option, but then I think it sould be version `3.0.0` as quite breaking change.
