### ISSUE TITLE
Question: Modules' name suggestion

### ISSUE THREAD

**Issue by emartynov** [jraska/modules-graph-assert#37]
I like the plugin idea but I also don't have a solution how to properly name modules in the big project.

Check the tivi app (https://github.com/chrisbanes/tivi) and try next configuration:

```
moduleGraphAssert {
    moduleLayers = [
            ':ui-\\S*',
            ':presenter-\\S*',
            ':common-\\S*',
            ':(base\\S*|data\\S*|domain|trakt-\\S*|tmdb|tasks)'
    ]
}
```

You will get:

```
 Direction of layers Regex ':ui-\S*' -> Regex ':presenter-\S*' -> Regex ':common-\S*' -> Regex ':(base\S*|data\S*|domain|trakt-\S*|tmdb|tasks)' violated. The violating dependencies are: 
   Module ':base-android' cannot depend on ':base'.
   Module ':base-android' cannot depend on ':data'.
   Module ':data' cannot depend on ':base'.
   Module ':data' cannot depend on ':tmdb'.
   Module ':tmdb' cannot depend on ':base'.
   Module ':common-ui-view' cannot depend on ':common-ui-resources'.
   Module ':common-epoxy' cannot depend on ':common-ui-view'.
   Module ':common-imageloading' cannot depend on ':common-ui-view'.
   Module ':common-databinding' cannot depend on ':common-ui-view'.
   Module ':common-entrygrid' cannot depend on ':common-ui-view'.
   Module ':common-entrygrid' cannot depend on ':common-epoxy'.
   Module ':common-entrygrid' cannot depend on ':common-layouts'.
   Module ':common-entrygrid' cannot depend on ':common-databinding'.
   Module ':domain' cannot depend on ':data'.
   Module ':domain' cannot depend on ':base'.
   Module ':domain' cannot depend on ':base-android'.
   Module ':domain' cannot depend on ':data-android'.
   Module ':domain' cannot depend on ':trakt-auth'.
   Module ':domain' cannot depend on ':tmdb'.
   Module ':data-android' cannot depend on ':data'.
   Module ':data-android' cannot depend on ':base'.
   Module ':data-android' cannot depend on ':base-android'.
   Module ':trakt-auth' cannot depend on ':base'.
   Module ':trakt-auth' cannot depend on ':base-android'.
   Module ':trakt-auth' cannot depend on ':data'.
   Module ':common-layouts' cannot depend on ':common-ui-view'.
   Module ':common-layouts' cannot depend on ':common-epoxy'.
   Module ':common-layouts' cannot depend on ':common-imageloading'.
   Module ':common-layouts' cannot depend on ':common-databinding'.
   Module ':tasks' cannot depend on ':base'.
   Module ':tasks' cannot depend on ':base-android'.
   Module ':tasks' cannot depend on ':domain'.
   Module ':ui-showdetails' cannot depend on ':ui-episodedetails'.
   Module ':ui-episodedetails' cannot depend on ':ui-episodedetails-compose'.
   Module ':common-ui-compose' cannot depend on ':common-imageloading'.
```

Obviously, there are cases when some common code should depend on some common code. And proposal of `common` -> `lib` -> `core` might be misleading and not enough.

I'm thinking about the structure of the module in this project so I will keep this thread with suggestions. Let me know if you have any thoughts.

P.S. This is just 30 modules project, imagine what happens in 100+ modules project

**Comment by jraska** [comment]
So there is `moduleLayersExclude` for cases where there is just few exceptions. In your case it feels like a lot.

Other option is to use `restricted` just to define some rules explicitly if layers do not work for the project.

let me know if you can imagine another asserting system :)

**Comment by jraska** [comment]
Hey, please would solution with capturing groups solve your problem: #49 . If yes we would have two issues calling for same solution and it is doable to implement the matching based on groups.

**Comment by jraska** [comment]
Please checkout the version `1.3.1` and let's see oif this can be solved somehow by using regex grouping. I can see some options for example with the `common-` modules etc.

**Comment by jraska** [comment]
Hey, closing this as inactive :) Please reopen this if more discussion is needed.

**Comment by emartynov** [comment]
Hi Josef, I'm sorry for not participating recently. I've changed job and my current project is just 4 modules mono repo. So your plugin will not be applicable to it at least for the next half of the year.

Please keep it closed and hopefully, there will be some more discussion later.

**Comment by jraska** [comment]
Hey Eugen, sure makes sense. Take care :)
