### ISSUE TITLE
Incremental run and laziness

### ISSUE THREAD

**Issue by emartynov** [jraska/modules-graph-assert#38]
I put here as a question and action for the future.

If I will apply this plugin in the project I would like to:
1. It doesn't harm the performance of my daily routines when I don't run
2. It is smart to reuse previous calculations if nothing was changed (probably not important since the time run of plugin is small)

**Comment by jraska** [comment]
Hey, regarding the build times I think (1.) laziness is more important and I will implement this https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

Regarding 2. do you have any ideas how to di it for in memory operation without any input? Basicalluy the input is all gradle scrips so I'm not sure if we can instruct Gradle what is the input to enable no-op tasks executions

**Comment by emartynov** [comment]
I would check gradle caching and reuse same output if input didn't change - the content of the gradle files

**Comment by jraska** [comment]
Yeah, the problem I see here is that the input is a dependency graph, which might actually change also programatically. If for example a custom plugin within `buildSrc` adds some dependencies to modules, gradle files will not change, but the modules graph yes.

Not sure if there is a way to put input for whole Gradle configuration?

**Comment by tasomaniac** [comment]
Any changes in `buildSrc` I validates caches I think. It might be also true with additional parameters sent to the build.

Btw, if you calculate the graph during configuration time (lazily), then that can be your input.

**Comment by jraska** [comment]
Resolved by [Release 2.0.0](https://github.com/jraska/modules-graph-assert/releases/tag/2.0.0)

**Comment by emartynov** [comment]
I'm back :)

Great to see configuration cache is supported. 
But how about just caching. I understand it is tricky. 

But what if sha of gradle and catalogue is used as input - would it be possible to reuse cache if input is not changed?

(Sure there might be logic based on the build parameter, environment variable, date/time).
