### ISSUE TITLE
> Dependency Tree is empty

### ISSUE THREAD

**Issue by tobiasKaminsky** [jraska/modules-graph-assert#42]
Hi,

thanks for the plugin, which I tried to use.
My app does not (yet) have a separate app folder structure and therefore only one build.gradle.

So I added plugins (https://github.com/nextcloud/android/pull/5733) and ran
./gradlew generateModulesGraphvizText -Pmodules.graph.print.statistics=true

which then gave me:
```
> Task :generateModulesGraphvizText FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateModulesGraphvizText'.
> Dependency Tree is empty
```

Thank you!

**Comment by jraska** [comment]
Hi Tobias,

Thanks for trying the plugin!

In case there is only one module there are no dependencies to put in the graph.

I think this would resolve at the moment you have at least 2 modules with some dependency between them :) I think that is also the moment where the plugin will bring any value to you. 

Does this make sense?

**Comment by tobiasKaminsky** [comment]
Ah 🙈
I totally misread the usage of this plugin.
I thought it would show me the dependency graphs between classes.

Sorry for the noise!
