### ISSUE TITLE
Using plugin with modules without dependencies

### ISSUE THREAD

**Issue by ILikeYourHat** [jraska/modules-graph-assert#51]
Hi 🙂 
I have a project with probably 30+ modules. I also have a common gradle file, that is included in each of those modules. I want to add this plugin through this file, but unfortunately this is causing errors in some of my modules: `Dependency Tree is empty`. 

Is there a way to ignore this error for modules without dependencies? I want to avoid adding you plugin in each of my modules separately.

**Comment by jraska** [comment]
Hi thanks for reporting this. There is not a way now, but I plan to implement it soon. 

It is not very descriptive the way the error is reported. Also you are not the first one reporting this so it will get a priority :)

**Comment by jraska** [comment]
Please try the [latest release](https://github.com/jraska/modules-graph-assert/releases) and let me know if the problem is solved.

**Comment by ILikeYourHat** [comment]
This works as expected now, thank you! 😄
