### ISSUE TITLE
Support for nested modules

### ISSUE THREAD

**Issue by ILikeYourHat** [jraska/modules-graph-assert#56]
Hi 😄  Let's say we have following modules: `:app`, `:first`, and `:first:second` (nested module). The dependencies are: `:app` -> `:first` and `:first -> :first:second`. This works as expected in assembled project, but `:first -> :first:second` dependency is not visible in generated graph. Tested it in a bigger project, and all nested modules are ignored 😢  Can you add support for them?

**Comment by jraska** [comment]
HI, thanks for reporting this. Let me check if I can reproduce this and how the Gradle model looks like in this case. Hopefully the fix is easy.

**Comment by jraska** [comment]
I tried and seems to work well. Please see the PR #58 
<img width="509" alt="Screenshot 2020-05-23 at 16 25 22" src="https://user-images.githubusercontent.com/6277721/82733136-25f4e500-9d12-11ea-9efb-554d9bfcd2c9.png">


Could you provide more info or a standalone example please? Or isn't it the configure on demand again?

**Comment by ILikeYourHat** [comment]
Nevermind, I've changed the generated file path and was looking at the old graph all the time... Sorry for trouble, and I promise from now I will check everything ten times before submitting a bug 🙈

Btw, great job with this plugin 😄 It makes managing big projects a lot easier, and It's really useful. Thank you 🙂

**Comment by jraska** [comment]
Cool, thanks for coming back with this! Most people just don't reply at the moment they realise they submitted no-bug as bug so I appreciate it. :)

And thanks for feedback 👍
