### ISSUE TITLE
Save graphviz to dot file

### ISSUE THREAD

**Issue by dafi** [jraska/modules-graph-assert#7]
Should be useful to save the graphViz output to separated `.dot` file to simplify using it with graphviz tools 

I would like a command line argument (eg `modules.graph.dot.path`)

    ./gradlew generateModulesGrapvizText -Pmodules.graph.dot.path=~/myproject/allmodules.dot

**Comment by jraska** [comment]
Hey, thanks a lot for the idea, I completely agree.

I think I will implement this once I will have some time to iterate a bit on this library - end of January.

Also, PR is always welcome ;)

**Comment by dafi** [comment]
> Also, PR is always welcome ;)

Ok, PR created

Now it's much better for me

    ./gradlew generateModulesGrapvizText -Pmodules.graph.output.gv=../photoshelf && dot -Tpng ../photoshelf.gv -O | open ../photoshelf.gv.png

**Comment by jraska** [comment]
Resolved by #8
